aliases:
 - &filter-only-source
   branches:
     only:
       - source

version: 2
jobs:
  deploy-website:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15.2

    steps:
      - add_ssh_keys:
          fingerprints:
            # This key added by @kaichao
            - "12:00:9f:21:a5:df:e0:fc:67:8d:13:37:16:8f:67:f1"
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "subdev-deploy@users.noreply.github.com"
            git config --global user.name "SubDev"
            # install Docusaurus and generate file of English strings
            yarn install
            # build and publish website
            USE_SSH=true GIT_USER=git yarn run publish-gh-pages

  check-build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15.2

    steps:
      - add_ssh_keys:
          fingerprints:
            # This key added by @kaichao
            - "12:00:9f:21:a5:df:e0:fc:67:8d:13:37:16:8f:67:f1"
      - checkout
      - run:
          name: Check if Site Builds
          command: |
            cd website && yarn install && yarn build

workflows:
  version: 2
  commit_deploy:
    jobs:
      - deploy-website:
          filters: *filter-only-source
  check_build:
    jobs:
      - check-build
